// ---------------------------------------------------------------------------
// California, as a relief-carvable heightfield
// ---------------------------------------------------------------------------
//
// A geographically accurate terrain model of the state, sized for a 35 mm tall
// carving in a 50 x 40 x 40 mm block. It exists to be fed to the relief carve
// exporter, so it is built the way that exporter wants its input: a closed solid
// whose plan view is the state's real outline and whose top surface is the real
// terrain.
//
// PROJECTION
//   EPSG:3310, "California Albers" -- Albers Equal Area Conic on GRS80, standard
//   parallels 34 N and 40.5 N, central meridian 120 W. That is the state's own
//   official projection, which is what makes the outline the shape California is
//   actually drawn as rather than the stretched one a plate carree gives you.
//   Equal-area also means a square centimetre of carving is the same number of
//   square kilometres wherever it falls on the block.
//
// SOURCES
//   Outline   -- US Census state boundary, rasterised to 4307 land cells.
//                3 corner-only connections filled so the mask is edge
//                connected and the solid built from it is a manifold; each costs
//                one 0.32 mm cell, well below what the finishing tool resolves.
//   Elevation -- AWS open terrain tiles (terrarium encoding) at zoom 7, roughly
//                1 km per pixel at this latitude, bilinearly resampled onto the
//                projected grid. The sample floor is held at the Badwater datum
//                so that a coastal cell which catches a little continental shelf
//                in its bilinear footprint cannot cut a trench inside the shore.
//
// SCALE
//   Plan view : 914.0 km east-west x 1054.5 km north-south, carved at
//               30.34 mm x 35.00 mm -- about 1 mm to 30.13 km.
//   Elevation : -86 m (Badwater Basin) to 3856 m, spread over 90% of the carve
//               depth. The Sierra crest reads 3856 m rather than Whitney's 4421
//               because a ~1 km posting averages a summit away; the ridge line is
//               right, the last 450 m of the peak is not there to be carved.
//               At plan scale that range would stand 0.131 mm proud, so the
//               18.00 mm of carved terrain exaggerates height 138x.
//   Depth     : 20.0 mm, chosen. Z runs from the Sierra crest at the stock's
//               top face down to the background floor at -20.0, with the
//               coastline cut to Z -17.6 and Badwater at -18.0.
//
//               138x is far past what a relief map would use -- this preset is a
//               sculpture of California, not a scale model of it. Carved at true
//               vertical scale the whole Sierra would be 0.131 mm proud of the
//               coast, which reads as a flat board, so every relief exaggerates;
//               this one just commits. What it costs is that slopes go near
//               vertical, so the tool has to be able to reach 20 mm down a
//               steep wall -- see the settings at the bottom of this file.
//
// The remaining 10% of the depth is a plinth under the lowest land, which is
// what gives the coastline a crisp step to stand proud of the background rather
// than fading into it at the floor.
//
// Regenerated by scripts/gen_california_relief.py -- the grid below is not
// hand-editable. The script re-fetches its sources, so a rerun needs a network.

import type { SceneGraph } from '../types/scene';
import type { ReliefCarveOptions } from '../utils/reliefCarveExporter';

/** Grid columns, west to east. */
export const CA_COLS = 94;
/** Grid rows, south to north. */
export const CA_ROWS = 108;
/** Carved plan-view size in mm. Height is the 35 mm the design is pinned to. */
export const CA_MAP_WIDTH_MM = 30.3358;
export const CA_MAP_HEIGHT_MM = 35.0;
/** Projected aspect ratio, width / height. */
export const CA_ASPECT = 0.866737;
/** Relief depth the design works out to, in mm. See the note on exaggeration above. */
export const CA_CARVE_DEPTH_MM = 20.000;
/** How much the height is stretched relative to the plan. */
export const CA_EXAGGERATION = 137.6;
/** Elevation the quantised grid's 0 and 255 stand for, in metres. */
export const CA_ELEV_MIN_M = -86.0;
export const CA_ELEV_MAX_M = 3856.3;
/** Share of the model's total height that sits below the lowest land. */
export const CA_PLINTH_FRACTION = 0.1;

// A bit-packed land mask (row-major, south row first) followed by one byte of
// elevation per cell. Base64 rather than a number literal: the same data as an
// array of 10152 integers is about six times the source size, and this file
// is read by people who want the projection notes at the top, not the samples.
const CA_GRID_B64 =
  'AAAAAAAAAAA8AAAAAAAAAAAAAAD/8AAAAAAAAAAAAAf//4AAAAAAAAADAB////gAAAAAAAAIAH////AAAAAAAAAAAf///8AAAAAAAAAAD////gAAAAAABAAAf///4AAAAAAAAAYB////wAAAAAAAABAP///+AAAAAAAAAAD////4AAAAAAAAAAf////wAAAAAAAAAD/////AAAAAAAAAD/////+AAAAAAAAAP/////4AAAAAAQAB//////gAAAAAEKAH/////+AAAAAAAAf//////4AAAAAAAD///////gAAAAAAAf///////AAAAAAAH///////+AAAAACf////////8AAAAAf/////////gAAAAB/////////8AAAAAH/////////gAAAAAf////////+AAAAAD/////////wAAAAAP////////+AAAAAAf////////4AAAAAD/////////AAAAAA/////////4AAAAAD/////////AAAAAAP////////4AAAAAB/////////AAAAAAP////////4AAAAAD////////+AAAAAAP////////wAAAAAB////////+AAAAAAH////////wAAAAAA////////+AAAAAAH////////wAAAAAA////////+AAAAAAH////////gAAAAAAf///////8AAAAAAB////////gAAAAAAH///////8AAAAAAAP///////gAAAAAAA///////8AAAAAAAD///////gAAAAAAAP//////4AAAAAAAH///////AAAAAAAA///////4AAAAAAAH///////AAAAAAAA///////4AAAAAAAB///////AAAAAAAAP//////4AAAAAAAA//////+AAAAAAAACf/////wAAAAAAAAJ/////+AAAAAAAAA//////wAAAAAAAAH/////+AAAAAAAAB3/////wAAAAAAAAfP////+AAAAAAAAA//////gAAAAAAAAD/////8AAAAAAAAAP/////gAAAAAAAAB/////8AAAAAAAAAP/////gAAAAAAAAB/////8AAAAAAAAAP/////gAAAAAAAAB/////4AAAAAAAAAP/////AAAAAAAAAA/////4AAAAAAAAAH/////AAAAAAAAAAP////8AAAAAAAAAB/////wAAAAAAAAAH/////AAAAAAAAAAf////8AAAAAAAAAB/////wAAAAAAAAAH/////AAAAAAAAAAf////8AAAAAAAAAB/////wAAAAAAAAAH/////AAAAAAAAAA/////8AAAAAAAAAD/////wAAAAAAAAAf/////AAAAAAAAAD/////8AAAAAAAAAf/////wAAAAAAAAD//////AAAAAAAAAP/////8AAAAAAAAA//////wAAAAAAAAD//////AAAAAAAAAH/////8AAAAAAAAAf/////wAAAAAAAAA//////AAAAAAAAAB/////8AAAAAAAAAH/////wAAAAAAAAAf/////AAAAAAAAAB/////8AAAAAAAAAH/////wAAAAAAAAAf/////AAAAAAAAAB/////8AAAAAAAAAH/////wAAAAAAAAAf/////AAAAAAAAAB/////8AAAAAAAAAP/////wAAAAAAAAA//////AAAAAAAAAB//8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhAaFgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcOIRsbNjxJSj9CGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgMDxUyNFVKXVI5HAwIBwUFBgYHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlAAAAAAAAAAAAAAANEQwbKjpUbnAoHyILBwUFBQUFBggICgoJCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAAAAAAAAAAAAAAADBUXJShGWXFFIBQOCgcGBAMEBQcIDAwQEAwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgTLCMoQ2EwLC0TJAcKBwQDBAUIDA0QFBUTCwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwbExgmOUtPM0A1EwYEBgICAwMHCwwRFRoPDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANAAAAAAAAAAAAAAAAAAAAAAAAAAYMFyAoME1fUFMgFAkIBwEBAQIECg8VJBsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAAAAAAAAAIDQ4cGzNBQl5KEBcPBwMBAQEDCBMmIh4YEwoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaAAAAAAAAAAAQEBIRDlByRWBoODUVKAYBAQECCQ8lIBsXEg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkPEDUaHyIwMF1pQjtDbhABAQMDFBsiLyYeFxwOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEOEDMrKRwiMzxNVGWhUhYCAQMEETIzNTQrHBUUDAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcMEBw6MCQkJjVUVmJfUCwEAg0ZQCwmLEY2GBEPDw0KAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0GBgYHCCJHMyIjJCMsNFt7KSAOBQokKyomIjMxGRANDRcOCwsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHBwYHCRAoJyAsKiIwJUZ9kw8MCBInSktHQDcdEg8RGBEbEA8MAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAAAAAAAAAAAAAAAAAAAAICAcICwwbFhEUISQxLTZMSiIRHRc2YlpNNDI6HBQQES8VGBUxDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAiABoAAAAAAAAAAAAABwkJCRQPGhMUGBc2KjRIQk0yHD1LaVZDLzgjHx0yFBcmMBgbJwwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABclKhQeJBQNEg0MERocGxwbGyQ+nqBhUTtjXVRhTjcvLjUoQhoyHhwUFRcOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcHEx4lFhQUEyAeJCMrPTYpIyVAU4WbpXdaSTo4MC4jICAtLhwcGhYXGBceFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0IDw8XGSAaGyVGZFI/WIh4PGxxc6GLkJl1W0g+NikqIiNFMCMSIhgSHCweFxUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhcSFw0PIy86JUBPcWV1fqWkYVZPRWeNi3hhVk8+OC06Mi41HSETERISFSlAKxweHxgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAgKDg4gMzksGTFFFSomGiEsMz9aXVdeWVNOSD9LQ0REQj05NkExOC4lJBIVERUiIhowPiMjK0MpHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABURHhUaLRcaKTVsTFpYWU43KyYzP0tTQD5AQ0VGQ0A/QU0+RE0/PjpASTQvExERExUeQTEeJyoeGxgYEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCRYSFB0qQ1hQXWyCb2h/az1HTkZIOTg4OjxAPj06QUhWSlNQRz4/RTQgFRMSFxQZJ1VDKCUjICYbDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADhcZFx5BUGdXWmlPXXJuXkNOZ1M8NjM0NTc/QEs8OEVOTFR0V1xUMjEzKCYpOCorIyQ8QCwxKCc3FgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABERHBczKzZLXUZAXHKvcXBhRT87ODY0MzMzPUA/Ojg3Oz1KUkg0LjEzJDc5O0VGNkEnLUovLi8vIRMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoIDg0kJzFlSzg2RVdqW0xHUWFWTD47OTc1MzZBPjw2NzI3LywrKSw/KyE2MS5ZU0MzLS06MS0uHRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAICAwVJDJbMCoxRDgmIiwrHBpQeWJcQkQ3NjMzOjk1MjM0PS86KikvPC8zPi4nOUJZPTk1NzI5IRUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0cHC0xJDRFMTcrEQ8PDRAVKGZ6ZVI9OTk0Njk4My4uOUpALSkuJyohHR8fKi43ZUxGRj43LScPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoNGh8uMDoxLDkpFw8LCwsMDlxdUV1mSzg0ODk7Ozw2TT9JOyszQiwjHBoYHzxON1NjV1NIPi4+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGBgKNDUzQywxKzczHRcRDAwMDRAfPFJcZV83MD5AP0M/SkRBREdGODAmIUIiGSQ8U09RbGRWTjkyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYMJB8mMy84LTQ2GBINCwwNDQ4VHz1RSXJRQC8tSUk7O1NWQ0VFQjlOKSs1JhwoRFVrWGl2W1Q4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOIxomMicrLzcxGg8LDAwMDQ8WFDpkUH6Db1FFSzVFTEdHV1RPSUxAOzYzHRgoN09XXlxEUmVeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPIyIeHCMjIjIyGRIMCwsMDQ8ZGS4/WF+AemlPQ1tDRDs4N0U/RExEWVZHUzEZMlRYT1txO0JdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOOiUfFx4fIDArGxMPCwsLDA0SGB84R2c6bV5vXk48OTtFLDNDLjVIQTJFSFIeGjRHSkqTSDlIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAccNCAkGBUZIyIsGBIQDAoKCgsMERcZO0WCTDs7XGVxNjQyLCkmTCtMTUEwGBMQEhwrQ0NKYUQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaMCAeGRYdIywdLxUQDQoKCgoKDA8UGz9Hh1ZpkmhrZjMxMD80JV0tLkw8KwsMHBcpOnFNVTgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhKhsbFxEWHywkJi0XDwsKCgoKCgwPERcqR4Rqqpl2h1s8NjVaTiwmVTojRyYGKi0eMD5eRjkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPh8YGiQSHiUwNUMgFBIJCQkJCgoMDRAcLFx7WbOZd51eUjVGh2RCIVU9KgoLMkYmITA6Qj4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMzIcHR8TFiwwQCMdFRoLCQkJCQoLDA0PHStHl2SzsYWmSFpVcHZWIkqGXw8BXFI2MjZCPTkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANE5ENxsQFx8lPC8cEhENCwkJCgoKCwwNEBcugJF+gai4lltpcnmJPxtaqj0DAWdLUyw3XDcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAITskKycQEB4hPlAnHBkODAsKCgoKCwsMDRIoKXanf3yypYFXhZ9phjMlZZ4xAD1oWDksWTcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEJQLTANChkdL0hNQz0VDAsKCgoKCwsMDQ4XMWiRwrbDybdSVJBoaWgpQWSbHgBGTzsuOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADA5J0ceChUcL0VLUycXDgsKCgoKCwsLDA0OEzRrrNvTubrSWUxadGguJWB5fA8CNkBILwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAhETAgCSIlJTRFKi8sEQwKCQkKCgsLDAwNEBs0XqvQrd3lzE1MW4FtOVdeYjoFDTtXMwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEA4mCBcyJDY2LB8hEQsKCQkKCgsMDAwNEB4tMmyDud/Y6nFOWKF9dJFiJ0QzABJRPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKBw48JygqNiQtDwwKCQkKCgoLDA0NDhI2RnKXwMvx/5RiTsJcLklvURQFBAoxPwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABggeKRcpND0ZHgwLCQkJCgsLDAwNDhkmLnGCjbK74ulwUXuKGx9dZ1oIBhg3WgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYRDwwTKCo2HQ0JCQgJCQoLDA0NDhcVJktrYpR/p9/zXFCwMyphWoViDBFYWwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGDRAJIjgjFhYJCAgICQoLCwwMEhMpIDVDarx1xuTzyVF3q0xGRZWPPSdoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgkQEhUJHyMlFxEJBwgICAkKCwwNEhEhQzNLcJG2vNK65pVSoMdvcmucOy5gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIhAYLhwOHjAgGxMICAcICAkKCwwNEBoaG01lga2+pd3n3tuCUqqfdWdAYTdXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHSQYIR4QGSswJB8SCAgHCAgJCgsMEhgfMTVJV561xcvH+8zKblWNlnRBWUlSAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBocJQsJFSs7LS8fCQcHBwgICQoMExsXIUJYd0aoqrzRx/yvpFSbj41dSo1NAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUIgsHBy1JMkEsHAgHBwgJCQoMDxgoJD9BYJBXe4uXxPrReV1WoZRqVHGJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMKAkGBQ86ODwrGxQHBwcICQoPEBsiJjI9bYGKimKjxdTgymFgWL+4mHN7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFg0GBgYhOCU3Ih8IBgcICQsKDBAcK0ROWFd9paiZj6fZ2ZqAYmLgvX8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAYcERwvIhYJBgcHCAkKCg8cLSg6UVmKs77SnLGvk4yahmaJ+YcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALAAAKFgwQHg4IBgYHCAkKCgsXHydCPVthZInIwe3QoJuMrZdmqrAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAUJFBEUHRIGBgYGBwgJCgwXGjBES1dndaugx9bkraStwq6BdfYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgwGGg8WGg0GBQUGBgcICQwaGh8qLlhHQYCgs6m864+do5ONjnwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFwYADRAJCxcJBgUFBgYHCQoTGB0rMzhmbGZ8hrq02OWFhIyQhpMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoIDxoJAAAPBQYFBQYFBQYHBwgNHCMiHz1Scn5+oKnEzOC8iYSFkpIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACRMUBwUFCgUGBwkFBQUGBwgNDx8bJT5HXmmEl6u31riunambkQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwNDQcFBg0GBgcGBQUGBgcJCwwcJDM/WGF4fa+vzqjAkou/swAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDQghDAoXCw8GBgYFBgYHCgoSIiA6RF9ggHGVj7+UmZKIqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAODgcZDyIIKTAQBwYGBgYHCAoLEyQ4O0pkgIiMqI7CwqTXkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVCAgICyQJHiEnCQcHBgYGBwkJDhknPE5ebV1sqbGvmK2FvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHhkQCx0QKRkOKQoIBwYGBgcJDRcaJzZKYm+Lppqjp4eQgQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASFCkSCgoXMxMdGSoJCAcGBgYICg0gJDA3VWZ+hKi3pIGfaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHFBsdFg8rLxwcIioUCQoHBgYHCAsQFSUpQFFRWY+Pq5R1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJFhMrHw0oPkgiKCgdFwsGBgYGBwgPFxwrNk5hZHOZqYnGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERgcIyscNjYwJDsYGxMJBgYGBgcIDCAjLz9MYnqLoZKBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiYoFCkaMiIrISUnIBULBwYGBgYHCQ4gLDU/P1pblpaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtEhoaFzYiHyQwNBcMCAYHBgYHBwoWKy8oTF50b4+kgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAaDhUlISA6IUozQyQaCAcHBwsHBwgRIzM+O1o8bYygg4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAERQUHSQmIzFFXC4fDQgHBwcIBwgNFhoqPk1ha4KLoIKBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4PHDM6IDM3SkYkJw8IBwcHBwcIDB4pKD5PTnaPlJyHeQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPGBMlMS5TL1N1KSMPCAcHBwcIChUpOTdSYVh7iZOYgnoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAChEzIjIuV4BQaR4XDgkIBwgICBIYITVLWFlOcISWd4uTAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABYSMyYrPkGAaVcbGREJCQgICQoSK0BLU15mbZKDaYJrhwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcMSdGJyRFTnYvKBURCwoJCAoVISEyP2tsdoOAX3BmZ20AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDcxHC0jQ15FWh4WEAwKCQkOIDQ1Z2t0T4SIXm9pZmduAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGyIuTzIzPjx5P1YcFhENCwkLICFGXjJwel5oVoJ5i4Z2lwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACQgLiUdPVtdb1p6JhQSDQsLEy9NS3R+Xm9eWo+GeHSTel8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACcUMjMTRSphbo59aCAUEA0KDR4uMFlwhF5pdE1oZnJ/eHdZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQXIS0pMzlKUHV1Zy8eFRANCxgpKU5Ke3ZldVxlUHtvgFVVVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACkeJBsfEzRBPFZZYlUjGxQTDw8ZJjZUc2NnYWB/a3CAk1RUVFUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0OHCAYIiRnSGpNYz8wIR0TEREOFC82WmZoeGdubW9xZltiVVWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUKzYoJTBTUFZNTVNQNCMYExQSERcgPluNjnSGg3ZydV1nWHFfawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHBgUDyEmOEI8WExEXltHIxgRDxEfOlFZfoyMloR3e3NyZl9dX2gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAsPCCg/M1FOLlM6Ok9HXEomERERGSxEeHdoi3qHf4drcXdvbWN4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhkiNh5LVDs9dl8vNUkfPRgUFB45TGqgcm1zfXVybGp7enKJawAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYKHipFTDBjZS02TkU9QUsbHiYqNWZiY0pndXx1g35ufH9ucnQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABhISQWAbWFFoOIBBO1hZIClAKTNUR0pYV2NdXHV3bm5vcG92AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIFylCJkREh12FmT48TCM9Oiw+SUVDSVJOZnl0e35ufH9wgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADjo5PB1QO11ihn9YQFoxTjo7NU1NREdGTlhhcnxqeHF7f4cAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUbSg1aeUtfU2tlUXhkdEU8Q1hFaFFISHdXWFtqhYWLeJyOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtJ0AYRU1RRUt5fXxLeIZVT0NcX1pQTVFmWFpahHxoYGp+eQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHCw0Oh1bK1BAiWtdgIN0SmVSUVhpVGZeWl1vZHlyZ2R4oGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0mKkonND99XWJLY1qIUWfTc1tvYVpdXV5kYF1hXFxheZ5fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMHio/RScwYm6OQFJpY0BYiXuHbWxwaVpdY2ZoX1xcXoB+XgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAETAiVTc+eGqEWD1NWD06RFx2eXeIk5dgW2JoaWhnZ2d+hV4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkuSmk3Hlx0W087S2Q8OUdzZ2NgaIB4WVheZmhoaGhndGNdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZOS5CVy88XWQ1bGBHNj5HhnNeW2JhXlheYWFnZ2psYnCEXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEy0zUk5oHD5GOj1BMkw6WYNgW2FYW1VWXl5hZ2tobGJwiF4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABiEUHDlrOExFUEZpTlMyN0x0YFlmVlhVVWFiYWVtcnJiY5x2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfIEgzS0hYcklfcGVVT0JITQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA';

const B64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Decodes the payload without `atob` or `Buffer`.
 *
 * Neither is portable across the three places this module is loaded — a browser
 * has `atob` and no `Buffer`, a bare node test run has the reverse, and reaching
 * for whichever exists means the preset's type-checking depends on which one the
 * tsconfig happens to know about. Twelve lines avoids the question.
 */
function decodeBase64(s: string): Uint8Array {
  const pad = s.endsWith('==') ? 2 : s.endsWith('=') ? 1 : 0;
  const bytes = new Uint8Array((s.length / 4) * 3 - pad);
  let out = 0;
  for (let i = 0; i < s.length; i += 4) {
    const n =
      (B64_ALPHABET.indexOf(s[i]) << 18) |
      (B64_ALPHABET.indexOf(s[i + 1]) << 12) |
      (Math.max(0, B64_ALPHABET.indexOf(s[i + 2])) << 6) |
      Math.max(0, B64_ALPHABET.indexOf(s[i + 3]));
    if (out < bytes.length) bytes[out++] = (n >> 16) & 0xff;
    if (out < bytes.length) bytes[out++] = (n >> 8) & 0xff;
    if (out < bytes.length) bytes[out++] = n & 0xff;
  }
  return bytes;
}

function decodeGrid(): { mask: Uint8Array; elev: Uint8Array } {
  const bytes = decodeBase64(CA_GRID_B64);
  const cells = CA_COLS * CA_ROWS;
  const packedLen = Math.ceil(cells / 8);
  const mask = new Uint8Array(cells);
  for (let i = 0; i < cells; i++) {
    mask[i] = (bytes[i >> 3] >> (7 - (i & 7))) & 1;
  }
  return { mask, elev: bytes.subarray(packedLen, packedLen + cells) };
}

export interface CaliforniaMesh {
  vertices: number[];
  faces: number[];
  /** Land cells that made it into the surface. */
  landCells: number;
}

/**
 * Expands the grid into a closed solid.
 *
 * Closed, not a bare surface, for two reasons. The relief exporter drops a ray
 * down each grid cell and keeps the highest triangle, which an open sheet would
 * satisfy -- but it also checks each solid's signed volume to decide whether the
 * winding is inside out, and an open sheet has no volume to sign. And the 3D
 * viewport draws this thing; a state with no sides to it looks like a decal.
 *
 * Vertices come out in three.js Y-up space, which is what a mesh geom's
 * `vertices` field is defined to hold: x east, y elevation, z south.
 */
export function buildCaliforniaMesh(): CaliforniaMesh {
  const { mask, elev } = decodeGrid();

  const cols = CA_COLS;
  const rows = CA_ROWS;
  // Scene units are metres and the exporter reads 1 m as 1000 mm, so a 120 mm
  // map is authored 0.120 long and carves at 100% scale with no fitting.
  const w = CA_MAP_WIDTH_MM / 1000;
  const h = CA_MAP_HEIGHT_MM / 1000;
  const dx = w / cols;
  const dy = h / rows;

  // The mesh is built at the proportions it is meant to be carved at, so a
  // carve depth of CA_CARVE_DEPTH_MM reproduces this solid exactly. That matters
  // because the exporter can either stretch the model's height range onto the
  // carve depth or keep it on the plan scale, and if the mesh were authored at
  // some other height the two would disagree about what the model looks like.
  // Terrain occupies 1 - plinth of that depth; the plinth is the rest.
  const depth = CA_CARVE_DEPTH_MM / 1000;
  const terrainSpan = depth * (1 - CA_PLINTH_FRACTION);
  const baseY = -depth * CA_PLINTH_FRACTION;
  const cellY = (i: number) => (elev[i] / 255) * terrainSpan;

  const at = (c: number, r: number) => r * cols + c;
  const isLand = (c: number, r: number) =>
    c >= 0 && c < cols && r >= 0 && r < rows && mask[at(c, r)] === 1;

  // Corner heights: the mean of whatever land cells touch that corner. A corner
  // with no land under it is never referenced.
  const cw = cols + 1;
  const cornerY = new Float64Array(cw * (rows + 1));
  const cornerN = new Uint8Array(cw * (rows + 1));
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (mask[at(c, r)] !== 1) continue;
      const y = cellY(at(c, r));
      for (const [oc, or_] of [[0, 0], [1, 0], [0, 1], [1, 1]] as const) {
        const k = (r + or_) * cw + (c + oc);
        cornerY[k] += y;
        cornerN[k]++;
      }
    }
  }
  for (let k = 0; k < cornerY.length; k++) if (cornerN[k] > 0) cornerY[k] /= cornerN[k];

  const vertices: number[] = [];
  const faces: number[] = [];
  const pushVert = (x: number, y: number, z: number) => {
    vertices.push(x, y, z);
    return vertices.length / 3 - 1;
  };

  // Plan-view position of a grid corner, centred on the origin. z is negated
  // because Y-up space runs +z south while the grid runs north.
  const px = (c: number) => -w / 2 + c * dx;
  const pz = (r: number) => h / 2 - r * dy;

  // Vertex indices are memoised per corner so adjacent quads share them and the
  // solid is actually welded rather than a soup of loose triangles.
  const topIdx = new Int32Array(cw * (rows + 1)).fill(-1);
  const botIdx = new Int32Array(cw * (rows + 1)).fill(-1);
  const top = (c: number, r: number) => {
    const k = r * cw + c;
    if (topIdx[k] < 0) topIdx[k] = pushVert(px(c), cornerY[k], pz(r));
    return topIdx[k];
  };
  const bot = (c: number, r: number) => {
    const k = r * cw + c;
    if (botIdx[k] < 0) botIdx[k] = pushVert(px(c), baseY, pz(r));
    return botIdx[k];
  };

  let landCells = 0;
  for (let r = 0; r < rows; r++) {
    for (let c = 0; c < cols; c++) {
      if (mask[at(c, r)] !== 1) continue;
      landCells++;

      // Top surface, wound counter-clockwise seen from above (+y).
      const a = top(c, r), b = top(c + 1, r), d = top(c + 1, r + 1), e = top(c, r + 1);
      faces.push(a, e, d, a, d, b);

      // Underside, wound the other way so the solid's normals all point out.
      const a2 = bot(c, r), b2 = bot(c + 1, r), d2 = bot(c + 1, r + 1), e2 = bot(c, r + 1);
      faces.push(a2, d2, e2, a2, b2, d2);

      // A wall on every edge the coast or the state line runs along.
      if (!isLand(c, r - 1)) faces.push(a, b, b2, a, b2, a2);
      if (!isLand(c + 1, r)) faces.push(b, d, d2, b, d2, b2);
      if (!isLand(c, r + 1)) faces.push(d, e, e2, d, e2, d2);
      if (!isLand(c - 1, r)) faces.push(e, a, a2, e, a2, e2);
    }
  }

  return { vertices, faces, landCells };
}

const caMesh = buildCaliforniaMesh();

export const californiaReliefPreset: SceneGraph = {
  nodes: [
    {
      id: 'california',
      name: 'california',
      type: 'body',
      pos: [0, 0, 0],
      geoms: [
        {
          name: 'california_terrain',
          type: 'mesh',
          size: [1],
          vertices: caMesh.vertices,
          faces: caMesh.faces,
          rgba: [0.72, 0.66, 0.52, 1],
          // Loads with no joint (below) and stays contype/conaffinity default
          // (normal collision) rather than 0/0: this used to disable collision
          // outright on the reasoning that a body which never moves has no
          // need for it, but contype:0/conaffinity:0 disables collision with
          // EVERYTHING, including the ground — so a joint added later (to
          // make it draggable) sends it falling straight through the floor
          // with nothing to catch it. A six-figure triangle mesh does cost a
          // real amount to convex-hull if it ever becomes a jointed,
          // interactive body, but that's the deliberate tradeoff once that's
          // wanted, not a mistake to optimize away by default.
        },
      ],
      joints: [],
      children: [],
    },
  ],
};

/**
 * What this model is, as far as the carve exporter is concerned: a 50 x 40 x 40 mm
 * block with the map pinned to 35 mm north-south and cut 20 mm deep.
 *
 * `manual` at 100% rather than `fit` is the whole point. Fitting would scale the
 * state to fill the stock, and the depth is derived from the plan size, so a
 * plan the design did not choose gives an exaggeration it did not choose either.
 * The size is carried by the mesh being authored at 0.035 m and the exporter
 * being told not to rescale it.
 *
 * There is deliberately no tooling in here. Which cutter reaches the bottom of a
 * 20 mm wall, how fast it should be fed and what it has to be ground on are
 * facts about a machine and a workshop, not about California. The exporter works
 * them out from the depth and the plan size -- see `recommendReliefTooling` --
 * which is also what lets this model be carved on stock it was never designed
 * for. What belongs here is the object: how big it is, how deep it is, and that
 * its height is already in the mesh rather than something to be stretched onto
 * the stock.
 */
export const CALIFORNIA_RELIEF_SETTINGS: Partial<ReliefCarveOptions> = {
  stockWidthMm: 50,
  stockDepthMm: 40,
  stockThicknessMm: 40,
  carveDepthMm: CA_CARVE_DEPTH_MM,
  // The mesh is authored at exactly these proportions, so 'fill' and
  // 'proportional' at 1x agree; 'fill' is kept because it is the exporter's
  // default and needs no exaggeration figure alongside it.
  verticalScaleMode: 'fill',
  verticalExaggeration: 1,
  fitMode: 'manual',
  scalePercent: 100,
  // The state has to stand proud of something, so the sea is cut away too.
  backgroundMode: 'carve',
};
